[project]
name = "llama-diffusion-projector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "aiohttp>=3.13.5",
    "fastparquet>=2026.5.0",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "tqdm>=4.67.3",
    "transformers>=4.51.0",
    "python-dotenv>=1.0.0",
    "gguf>=0.19.0",
]
[project.optional-dependencies]
nvidia = [
    "torch==2.9.0",
    "torchvision==0.24.0",
    "torchaudio==2.9.0",
    "flash-attn==2.8.3 ; sys_platform != 'win32'",
    "triton==3.5.0 ; sys_platform != 'win32'",
]

[tool.uv]
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
no-binary-package = ["flash-attn"]

[tool.uv.extra-build-dependencies]
flash-attn = ["torch==2.9.0"]
