#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

# Keep the current MLP projector path, but make scale matching a first-class
# objective so the exported SDXL tensors are less likely to need downstream
# normalization. The pooled head is de-emphasized slightly to avoid buying
# image quality at the expense of token-level prompt control.
export TARGET_OUTPUT_DIR="${TARGET_OUTPUT_DIR:-embedded_chunks/run-1m-2560}"
export TRAIN_TARGET_FAMILY="${TRAIN_TARGET_FAMILY:-sdxl}"
export CPU_THREADS="${CPU_THREADS:-8}"
export TRAIN_ARCHIVE_THREADS="${TRAIN_ARCHIVE_THREADS:-2}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-512}"
export TRAIN_EPOCHS="${TRAIN_EPOCHS:-50}"
export TRAIN_VAL_SPLIT="${TRAIN_VAL_SPLIT:-0.05}"
export TRAIN_MAX_LR="${TRAIN_MAX_LR:-8e-5}"
export TRAIN_WEIGHT_DECAY="${TRAIN_WEIGHT_DECAY:-1e-5}"
export TRAIN_PCT_START="${TRAIN_PCT_START:-0.10}"
export TRAIN_GRAD_CLIP="${TRAIN_GRAD_CLIP:-1.0}"
export TRAIN_HIDDEN_DIM="${TRAIN_HIDDEN_DIM:-4096}"
export TRAIN_PROGRESS_EVERY="${TRAIN_PROGRESS_EVERY:-50}"
export TRAIN_PROGRESS_SECONDS="${TRAIN_PROGRESS_SECONDS:-30}"
export TRAIN_TIMING="${TRAIN_TIMING:-0}"
export TRAIN_MAX_STEPS="${TRAIN_MAX_STEPS:-0}"
export RUN_LABEL="${RUN_LABEL:-scale_guard_prompt_cos10_nr20_pr05}"

export TRAIN_SDXL_PROJECTOR_ARCH="${TRAIN_SDXL_PROJECTOR_ARCH:-mlp}"
export TRAIN_SDXL_PROMPT_LOSS_WEIGHT="${TRAIN_SDXL_PROMPT_LOSS_WEIGHT:-1.0}"
export TRAIN_SDXL_POOLED_LOSS_WEIGHT="${TRAIN_SDXL_POOLED_LOSS_WEIGHT:-1.0}"
export TRAIN_SDXL_POINTWISE_LOSS="${TRAIN_SDXL_POINTWISE_LOSS:-huber}"
export TRAIN_SDXL_HUBER_DELTA="${TRAIN_SDXL_HUBER_DELTA:-1.0}"
export TRAIN_SDXL_PROMPT_COSINE_WEIGHT="${TRAIN_SDXL_PROMPT_COSINE_WEIGHT:-0.10}"
export TRAIN_SDXL_POOLED_COSINE_WEIGHT="${TRAIN_SDXL_POOLED_COSINE_WEIGHT:-0.05}"
export TRAIN_SDXL_PROMPT_NORM_WEIGHT="${TRAIN_SDXL_PROMPT_NORM_WEIGHT:-0.20}"
export TRAIN_SDXL_POOLED_NORM_WEIGHT="${TRAIN_SDXL_POOLED_NORM_WEIGHT:-0.15}"
export TRAIN_SDXL_PROMPT_NORM_MATCH_WEIGHT="${TRAIN_SDXL_PROMPT_NORM_MATCH_WEIGHT:-0.0}"
export TRAIN_SDXL_POOLED_NORM_MATCH_WEIGHT="${TRAIN_SDXL_POOLED_NORM_MATCH_WEIGHT:-0.0}"
export TRAIN_SDXL_MONITOR_METRIC="${TRAIN_SDXL_MONITOR_METRIC:-composite}"
export TRAIN_SDXL_MONITOR_NORM_WEIGHT="${TRAIN_SDXL_MONITOR_NORM_WEIGHT:-0.10}"
export TRAIN_SDXL_MONITOR_STD_WEIGHT="${TRAIN_SDXL_MONITOR_STD_WEIGHT:-0.05}"
export TRAIN_SDXL_USE_OUTPUT_CALIBRATOR="${TRAIN_SDXL_USE_OUTPUT_CALIBRATOR:-0}"
export TRAIN_SDXL_PROMPT_TOKEN_DIM="${TRAIN_SDXL_PROMPT_TOKEN_DIM:-256}"
export TRAIN_SDXL_TRUNK_DEPTH="${TRAIN_SDXL_TRUNK_DEPTH:-1}"
export TRAIN_SDXL_RESIDUAL_TRUNK="${TRAIN_SDXL_RESIDUAL_TRUNK:-1}"
export TRAIN_SDXL_PROMPT_HEAD_DIM="${TRAIN_SDXL_PROMPT_HEAD_DIM:-512}"
export TRAIN_SDXL_POOLED_HEAD_DIM="${TRAIN_SDXL_POOLED_HEAD_DIM:-2048}"

exec "$ROOT_DIR/train_sdxl_optimized.sh"