#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

# v4 is a warm-started scale-lock fine-tune from the completed v3 checkpoint.
#
# Derived from the native-mode tensor audit of the exported v3 artifact:
# - residual prompt RMS scale-to-match SDXL: 0.56306547867397
# - residual pooled RMS scale-to-match SDXL: 0.3950532568952248
#
# We warm-start from the best v3 checkpoint, preserve its semantic direction,
# and apply those residual scale factors directly to the learned calibrator
# gains before training starts.
#
# Mean v3 gain -> derived v4 warm-start target mean gain:
# - prompt: 0.8305086493492126 * 0.56306547867397 = 0.467630750189
# - pooled: 1.038710117340088 * 0.3950532568952248 = 0.410345814825
export TARGET_OUTPUT_DIR="${TARGET_OUTPUT_DIR:-embedded_chunks/run-1m-2560}"
export QWEN_OUTPUT_DIR="${QWEN_OUTPUT_DIR:-embedded_chunks}"
export TRAIN_TARGET_FAMILY="${TRAIN_TARGET_FAMILY:-sdxl}"
export CPU_THREADS="${CPU_THREADS:-8}"
export TRAIN_ARCHIVE_THREADS="${TRAIN_ARCHIVE_THREADS:-2}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-512}"
export TRAIN_EPOCHS="${TRAIN_EPOCHS:-30}"
export TRAIN_VAL_SPLIT="${TRAIN_VAL_SPLIT:-0.05}"
export TRAIN_MAX_LR="${TRAIN_MAX_LR:-5e-5}"
export TRAIN_WEIGHT_DECAY="${TRAIN_WEIGHT_DECAY:-1e-5}"
export TRAIN_PCT_START="${TRAIN_PCT_START:-0.05}"
export TRAIN_GRAD_CLIP="${TRAIN_GRAD_CLIP:-1.0}"
export TRAIN_HIDDEN_DIM="${TRAIN_HIDDEN_DIM:-4096}"
export TRAIN_PROGRESS_EVERY="${TRAIN_PROGRESS_EVERY:-50}"
export TRAIN_PROGRESS_SECONDS="${TRAIN_PROGRESS_SECONDS:-30}"
export TRAIN_TIMING="${TRAIN_TIMING:-0}"
export TRAIN_MAX_STEPS="${TRAIN_MAX_STEPS:-0}"
export RUN_LABEL="${RUN_LABEL:-warm_v3_scale_lock_v4}"

export TRAIN_WARM_START_PATH="${TRAIN_WARM_START_PATH:-embedded_chunks/run-1m-2560/targets/sdxl/qwen_sdxl_projector_best_20260603_150916_full_mlp_calibrated_dnorm.pt}"
export TRAIN_WARM_START_STRICT="${TRAIN_WARM_START_STRICT:-1}"

export TRAIN_SDXL_PROJECTOR_ARCH="${TRAIN_SDXL_PROJECTOR_ARCH:-mlp}"
export TRAIN_SDXL_PROMPT_LOSS_WEIGHT="${TRAIN_SDXL_PROMPT_LOSS_WEIGHT:-1.0}"
export TRAIN_SDXL_POOLED_LOSS_WEIGHT="${TRAIN_SDXL_POOLED_LOSS_WEIGHT:-1.0}"
export TRAIN_SDXL_POINTWISE_LOSS="${TRAIN_SDXL_POINTWISE_LOSS:-huber}"
export TRAIN_SDXL_HUBER_DELTA="${TRAIN_SDXL_HUBER_DELTA:-1.0}"
export TRAIN_SDXL_PROMPT_COSINE_WEIGHT="${TRAIN_SDXL_PROMPT_COSINE_WEIGHT:-0.10}"
export TRAIN_SDXL_POOLED_COSINE_WEIGHT="${TRAIN_SDXL_POOLED_COSINE_WEIGHT:-0.05}"
export TRAIN_SDXL_PROMPT_NORM_WEIGHT="${TRAIN_SDXL_PROMPT_NORM_WEIGHT:-1.0}"
export TRAIN_SDXL_POOLED_NORM_WEIGHT="${TRAIN_SDXL_POOLED_NORM_WEIGHT:-1.0}"
export TRAIN_SDXL_PROMPT_NORM_MATCH_WEIGHT="${TRAIN_SDXL_PROMPT_NORM_MATCH_WEIGHT:-4e-5}"
export TRAIN_SDXL_POOLED_NORM_MATCH_WEIGHT="${TRAIN_SDXL_POOLED_NORM_MATCH_WEIGHT:-4e-2}"
export TRAIN_SDXL_MONITOR_METRIC="${TRAIN_SDXL_MONITOR_METRIC:-composite}"
export TRAIN_SDXL_MONITOR_NORM_WEIGHT="${TRAIN_SDXL_MONITOR_NORM_WEIGHT:-3.0}"
export TRAIN_SDXL_MONITOR_STD_WEIGHT="${TRAIN_SDXL_MONITOR_STD_WEIGHT:-1.5}"
export TRAIN_SDXL_USE_OUTPUT_CALIBRATOR="${TRAIN_SDXL_USE_OUTPUT_CALIBRATOR:-1}"
export TRAIN_SDXL_PROMPT_OUTPUT_CALIBRATOR_GAIN_SCALE="${TRAIN_SDXL_PROMPT_OUTPUT_CALIBRATOR_GAIN_SCALE:-0.56306547867397}"
export TRAIN_SDXL_POOLED_OUTPUT_CALIBRATOR_GAIN_SCALE="${TRAIN_SDXL_POOLED_OUTPUT_CALIBRATOR_GAIN_SCALE:-0.3950532568952248}"
export TRAIN_SDXL_PROMPT_TOKEN_DIM="${TRAIN_SDXL_PROMPT_TOKEN_DIM:-256}"
export TRAIN_SDXL_TRUNK_DEPTH="${TRAIN_SDXL_TRUNK_DEPTH:-1}"
export TRAIN_SDXL_RESIDUAL_TRUNK="${TRAIN_SDXL_RESIDUAL_TRUNK:-1}"
export TRAIN_SDXL_PROMPT_HEAD_DIM="${TRAIN_SDXL_PROMPT_HEAD_DIM:-512}"
export TRAIN_SDXL_POOLED_HEAD_DIM="${TRAIN_SDXL_POOLED_HEAD_DIM:-2048}"

exec "$ROOT_DIR/train_sdxl_optimized.sh"