#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

TARGET_OUTPUT_DIR="${TARGET_OUTPUT_DIR:-embedded_chunks/run-1m-2560}"
QWEN_OUTPUT_DIR="${QWEN_OUTPUT_DIR:-embedded_chunks}"
TRAIN_TARGET_FAMILY="${TRAIN_TARGET_FAMILY:-sdxl}"
CPU_THREADS="${CPU_THREADS:-8}"
TRAIN_MAX_STEPS="${TRAIN_MAX_STEPS:-0}"
TRAIN_MAX_SAMPLES="${TRAIN_MAX_SAMPLES:-0}"
TRAIN_TIMING="${TRAIN_TIMING:-0}"
RUN_LABEL="${RUN_LABEL:-}"
TRAIN_WARM_START_PATH="${TRAIN_WARM_START_PATH:-}"
TRAIN_WARM_START_STRICT="${TRAIN_WARM_START_STRICT:-1}"
TRAIN_AUTO_RESUME="${TRAIN_AUTO_RESUME:-0}"

TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-512}"

TRAIN_ARCHIVE_THREADS="${TRAIN_ARCHIVE_THREADS:-2}"
TRAIN_ARCHIVE_MODE="${TRAIN_ARCHIVE_MODE:-auto}"

TRAIN_EPOCHS="${TRAIN_EPOCHS:-50}"
TRAIN_VAL_SPLIT="${TRAIN_VAL_SPLIT:-0.10}"
TRAIN_VAL_MAX_STEPS="${TRAIN_VAL_MAX_STEPS:-0}"
TRAIN_VAL_EVERY_N_EPOCHS="${TRAIN_VAL_EVERY_N_EPOCHS:-1}"
TRAIN_STREAM_VAL_CACHE="${TRAIN_STREAM_VAL_CACHE:-0}"
TRAIN_MAX_LR="${TRAIN_MAX_LR:-1e-4}"
TRAIN_WEIGHT_DECAY="${TRAIN_WEIGHT_DECAY:-1e-5}"
TRAIN_PCT_START="${TRAIN_PCT_START:-0.1}"
TRAIN_GRAD_CLIP="${TRAIN_GRAD_CLIP:-1.0}"
TRAIN_HIDDEN_DIM="${TRAIN_HIDDEN_DIM:-4096}"
TRAIN_PROGRESS_EVERY="${TRAIN_PROGRESS_EVERY:-50}"
TRAIN_PROGRESS_SECONDS="${TRAIN_PROGRESS_SECONDS:-30}"
TRAIN_SDXL_PROMPT_LOSS_WEIGHT="${TRAIN_SDXL_PROMPT_LOSS_WEIGHT:-1.0}"
TRAIN_SDXL_POOLED_LOSS_WEIGHT="${TRAIN_SDXL_POOLED_LOSS_WEIGHT:-1.0}"
TRAIN_SDXL_POINTWISE_LOSS="${TRAIN_SDXL_POINTWISE_LOSS:-mse}"
TRAIN_SDXL_HUBER_DELTA="${TRAIN_SDXL_HUBER_DELTA:-1.0}"
TRAIN_SDXL_PROMPT_COSINE_WEIGHT="${TRAIN_SDXL_PROMPT_COSINE_WEIGHT:-0.05}"
TRAIN_SDXL_POOLED_COSINE_WEIGHT="${TRAIN_SDXL_POOLED_COSINE_WEIGHT:-0.05}"
TRAIN_SDXL_PROMPT_NORM_WEIGHT="${TRAIN_SDXL_PROMPT_NORM_WEIGHT:-0.05}"
TRAIN_SDXL_POOLED_NORM_WEIGHT="${TRAIN_SDXL_POOLED_NORM_WEIGHT:-0.05}"
TRAIN_SDXL_PROMPT_NORM_MATCH_WEIGHT="${TRAIN_SDXL_PROMPT_NORM_MATCH_WEIGHT:-0.0}"
TRAIN_SDXL_POOLED_NORM_MATCH_WEIGHT="${TRAIN_SDXL_POOLED_NORM_MATCH_WEIGHT:-0.0}"
TRAIN_STANDARDIZE_EMBEDDINGS="${TRAIN_STANDARDIZE_EMBEDDINGS:-0}"
TRAIN_STANDARDIZATION_EPS="${TRAIN_STANDARDIZATION_EPS:-1e-6}"
TRAIN_STANDARDIZATION_THREADS="${TRAIN_STANDARDIZATION_THREADS:-$TRAIN_ARCHIVE_THREADS}"
TRAIN_CACHE_STANDARDIZED_ARCHIVES="${TRAIN_CACHE_STANDARDIZED_ARCHIVES:-0}"
TRAIN_STANDARDIZED_ARCHIVE_CACHE_DIR="${TRAIN_STANDARDIZED_ARCHIVE_CACHE_DIR:-}"
TRAIN_STANDARDIZED_ARCHIVE_COMPRESS="${TRAIN_STANDARDIZED_ARCHIVE_COMPRESS:-0}"
TRAIN_STANDARDIZED_ARCHIVE_CACHE_DTYPE="${TRAIN_STANDARDIZED_ARCHIVE_CACHE_DTYPE:-source}"
TRAIN_SDXL_MONITOR_METRIC="${TRAIN_SDXL_MONITOR_METRIC:-mse}"
TRAIN_SDXL_MONITOR_NORM_WEIGHT="${TRAIN_SDXL_MONITOR_NORM_WEIGHT:-0.0}"
TRAIN_SDXL_MONITOR_STD_WEIGHT="${TRAIN_SDXL_MONITOR_STD_WEIGHT:-0.0}"
TRAIN_SDXL_MONITOR_PROMPT_NORM_MATCH_WEIGHT="${TRAIN_SDXL_MONITOR_PROMPT_NORM_MATCH_WEIGHT:-0.0}"
TRAIN_SDXL_MONITOR_POOLED_NORM_MATCH_WEIGHT="${TRAIN_SDXL_MONITOR_POOLED_NORM_MATCH_WEIGHT:-0.0}"
TRAIN_SDXL_PROJECTOR_ARCH="${TRAIN_SDXL_PROJECTOR_ARCH:-auto}"
TRAIN_SDXL_SPECTRAL_NORM="${TRAIN_SDXL_SPECTRAL_NORM:-0}"
TRAIN_SDXL_USE_OUTPUT_CALIBRATOR="${TRAIN_SDXL_USE_OUTPUT_CALIBRATOR:-0}"
TRAIN_SDXL_PROMPT_OUTPUT_CALIBRATOR_GAIN_SCALE="${TRAIN_SDXL_PROMPT_OUTPUT_CALIBRATOR_GAIN_SCALE:-1.0}"
TRAIN_SDXL_POOLED_OUTPUT_CALIBRATOR_GAIN_SCALE="${TRAIN_SDXL_POOLED_OUTPUT_CALIBRATOR_GAIN_SCALE:-1.0}"
TRAIN_SDXL_PROMPT_TOKEN_DIM="${TRAIN_SDXL_PROMPT_TOKEN_DIM:-256}"
TRAIN_SDXL_TRUNK_DEPTH="${TRAIN_SDXL_TRUNK_DEPTH:-1}"
TRAIN_SDXL_RESIDUAL_TRUNK="${TRAIN_SDXL_RESIDUAL_TRUNK:-1}"
TRAIN_SDXL_PROMPT_HEAD_DIM="${TRAIN_SDXL_PROMPT_HEAD_DIM:-512}"
TRAIN_SDXL_POOLED_HEAD_DIM="${TRAIN_SDXL_POOLED_HEAD_DIM:-2048}"
TRAIN_SDXL_RESAMPLER_DEPTH="${TRAIN_SDXL_RESAMPLER_DEPTH:-2}"
TRAIN_SDXL_RESAMPLER_HEADS="${TRAIN_SDXL_RESAMPLER_HEADS:-8}"
TRAIN_SDXL_RESAMPLER_FF_MULT="${TRAIN_SDXL_RESAMPLER_FF_MULT:-4}"
TRAIN_SDXL_RESAMPLER_POOLED_QUERIES="${TRAIN_SDXL_RESAMPLER_POOLED_QUERIES:-1}"

LOG_DIR="$TARGET_OUTPUT_DIR/logs"
mkdir -p "$LOG_DIR"
STAMP="$(date +%Y%m%d_%H%M%S)"

if [[ -z "$RUN_LABEL" && "$TRAIN_MAX_STEPS" != "0" ]]; then
    RUN_LABEL="probe"
fi

safe_label=""
if [[ -n "$RUN_LABEL" ]]; then
    safe_label="$(printf '%s' "$RUN_LABEL" | tr '[:space:]' '_' | tr -cd '[:alnum:]_.-')"
fi

if [[ -n "$safe_label" ]]; then
    LOG_PATH="$LOG_DIR/train_${TRAIN_TARGET_FAMILY}_${STAMP}_${safe_label}.log"
    DEFAULT_BEST_CHECKPOINT="$TARGET_OUTPUT_DIR/targets/$TRAIN_TARGET_FAMILY/qwen_${TRAIN_TARGET_FAMILY}_projector_best_${STAMP}_${safe_label}.pt"
    DEFAULT_GGUF_PATH="$TARGET_OUTPUT_DIR/qwen_${TRAIN_TARGET_FAMILY}_projector_${STAMP}_${safe_label}.gguf"
    DEFAULT_RESUME_CHECKPOINT="$TARGET_OUTPUT_DIR/targets/$TRAIN_TARGET_FAMILY/qwen_${TRAIN_TARGET_FAMILY}_projector_resume_${safe_label}.pt"
else
    LOG_PATH="$LOG_DIR/train_${TRAIN_TARGET_FAMILY}_$STAMP.log"
    DEFAULT_BEST_CHECKPOINT="$TARGET_OUTPUT_DIR/targets/$TRAIN_TARGET_FAMILY/qwen_${TRAIN_TARGET_FAMILY}_projector_best.pt"
    DEFAULT_GGUF_PATH="$TARGET_OUTPUT_DIR/qwen_${TRAIN_TARGET_FAMILY}_projector.gguf"
    DEFAULT_RESUME_CHECKPOINT="$TARGET_OUTPUT_DIR/targets/$TRAIN_TARGET_FAMILY/qwen_${TRAIN_TARGET_FAMILY}_projector_resume.pt"
fi

TRAIN_BEST_CHECKPOINT="${TRAIN_BEST_CHECKPOINT:-$DEFAULT_BEST_CHECKPOINT}"
TRAIN_GGUF_PATH="${TRAIN_GGUF_PATH:-$DEFAULT_GGUF_PATH}"
TRAIN_RESUME_CHECKPOINT="${TRAIN_RESUME_CHECKPOINT:-$DEFAULT_RESUME_CHECKPOINT}"

echo "Starting optimized SDXL projector training"
echo "Target output: $TARGET_OUTPUT_DIR"
echo "Qwen source: $QWEN_OUTPUT_DIR"
echo "Log: $LOG_PATH"
echo "CPU threads: $CPU_THREADS | batch size: $TRAIN_BATCH_SIZE | archive mode: $TRAIN_ARCHIVE_MODE | archive threads: $TRAIN_ARCHIVE_THREADS"
echo "Max steps: $TRAIN_MAX_STEPS | max samples: $TRAIN_MAX_SAMPLES | timing: $TRAIN_TIMING | label: ${safe_label:-default}"
echo "Validation: split=$TRAIN_VAL_SPLIT | max_steps=$TRAIN_VAL_MAX_STEPS | every_n_epochs=$TRAIN_VAL_EVERY_N_EPOCHS | stream_cache=$TRAIN_STREAM_VAL_CACHE"
echo "Warm start: ${TRAIN_WARM_START_PATH:-none} | strict: $TRAIN_WARM_START_STRICT"
echo "Auto resume: $TRAIN_AUTO_RESUME | resume checkpoint: $TRAIN_RESUME_CHECKPOINT"
echo "LR: $TRAIN_MAX_LR | pct_start: $TRAIN_PCT_START | hidden_dim: $TRAIN_HIDDEN_DIM"
echo "SDXL loss: pointwise=$TRAIN_SDXL_POINTWISE_LOSS cos=($TRAIN_SDXL_PROMPT_COSINE_WEIGHT,$TRAIN_SDXL_POOLED_COSINE_WEIGHT) log_norm=($TRAIN_SDXL_PROMPT_NORM_WEIGHT,$TRAIN_SDXL_POOLED_NORM_WEIGHT) direct_norm=($TRAIN_SDXL_PROMPT_NORM_MATCH_WEIGHT,$TRAIN_SDXL_POOLED_NORM_MATCH_WEIGHT) monitor=$TRAIN_SDXL_MONITOR_METRIC monitor_w=($TRAIN_SDXL_MONITOR_NORM_WEIGHT,$TRAIN_SDXL_MONITOR_STD_WEIGHT) monitor_dnorm=($TRAIN_SDXL_MONITOR_PROMPT_NORM_MATCH_WEIGHT,$TRAIN_SDXL_MONITOR_POOLED_NORM_MATCH_WEIGHT)"
echo "Standardization: enabled=$TRAIN_STANDARDIZE_EMBEDDINGS eps=$TRAIN_STANDARDIZATION_EPS threads=$TRAIN_STANDARDIZATION_THREADS"
echo "Standardized archive cache: enabled=$TRAIN_CACHE_STANDARDIZED_ARCHIVES dir=${TRAIN_STANDARDIZED_ARCHIVE_CACHE_DIR:-default} compress=$TRAIN_STANDARDIZED_ARCHIVE_COMPRESS dtype=$TRAIN_STANDARDIZED_ARCHIVE_CACHE_DTYPE"
if [[ "$TRAIN_SDXL_PROJECTOR_ARCH" == "resampler" ]]; then
    echo "SDXL arch: arch=$TRAIN_SDXL_PROJECTOR_ARCH depth=$TRAIN_SDXL_RESAMPLER_DEPTH heads=$TRAIN_SDXL_RESAMPLER_HEADS ff_mult=$TRAIN_SDXL_RESAMPLER_FF_MULT pooled_queries=$TRAIN_SDXL_RESAMPLER_POOLED_QUERIES prompt_head_dim=$TRAIN_SDXL_PROMPT_HEAD_DIM pooled_head_dim=$TRAIN_SDXL_POOLED_HEAD_DIM"
else
    echo "SDXL arch: arch=$TRAIN_SDXL_PROJECTOR_ARCH trunk_depth=$TRAIN_SDXL_TRUNK_DEPTH residual=$TRAIN_SDXL_RESIDUAL_TRUNK prompt_token_dim=$TRAIN_SDXL_PROMPT_TOKEN_DIM spectral_norm=$TRAIN_SDXL_SPECTRAL_NORM output_calibrator=$TRAIN_SDXL_USE_OUTPUT_CALIBRATOR gain_scale=($TRAIN_SDXL_PROMPT_OUTPUT_CALIBRATOR_GAIN_SCALE,$TRAIN_SDXL_POOLED_OUTPUT_CALIBRATOR_GAIN_SCALE) prompt_head_dim=$TRAIN_SDXL_PROMPT_HEAD_DIM pooled_head_dim=$TRAIN_SDXL_POOLED_HEAD_DIM"
fi
echo "Best checkpoint: $TRAIN_BEST_CHECKPOINT"
echo "GGUF output: $TRAIN_GGUF_PATH"

env \
    OMP_NUM_THREADS="$CPU_THREADS" \
    MKL_NUM_THREADS="$CPU_THREADS" \
    OPENBLAS_NUM_THREADS="$CPU_THREADS" \
    NUMEXPR_NUM_THREADS="$CPU_THREADS" \
    PYTHONUNBUFFERED="1" \
    PYTORCH_ALLOC_CONF="${PYTORCH_ALLOC_CONF:-expandable_segments:True}" \
    TRAIN_TARGET_FAMILY="$TRAIN_TARGET_FAMILY" \
    TARGET_OUTPUT_DIR="$TARGET_OUTPUT_DIR" \
    QWEN_OUTPUT_DIR="$QWEN_OUTPUT_DIR" \
    TRAIN_BATCH_SIZE="$TRAIN_BATCH_SIZE" \
    TRAIN_ARCHIVE_MODE="$TRAIN_ARCHIVE_MODE" \
    TRAIN_ARCHIVE_THREADS="$TRAIN_ARCHIVE_THREADS" \
    TRAIN_EPOCHS="$TRAIN_EPOCHS" \
    TRAIN_MAX_STEPS="$TRAIN_MAX_STEPS" \
    TRAIN_MAX_SAMPLES="$TRAIN_MAX_SAMPLES" \
    TRAIN_VAL_SPLIT="$TRAIN_VAL_SPLIT" \
    TRAIN_VAL_MAX_STEPS="$TRAIN_VAL_MAX_STEPS" \
    TRAIN_VAL_EVERY_N_EPOCHS="$TRAIN_VAL_EVERY_N_EPOCHS" \
    TRAIN_STREAM_VAL_CACHE="$TRAIN_STREAM_VAL_CACHE" \
    TRAIN_MAX_LR="$TRAIN_MAX_LR" \
    TRAIN_WEIGHT_DECAY="$TRAIN_WEIGHT_DECAY" \
    TRAIN_PCT_START="$TRAIN_PCT_START" \
    TRAIN_GRAD_CLIP="$TRAIN_GRAD_CLIP" \
    TRAIN_HIDDEN_DIM="$TRAIN_HIDDEN_DIM" \
    TRAIN_SDXL_PROMPT_LOSS_WEIGHT="$TRAIN_SDXL_PROMPT_LOSS_WEIGHT" \
    TRAIN_SDXL_POOLED_LOSS_WEIGHT="$TRAIN_SDXL_POOLED_LOSS_WEIGHT" \
    TRAIN_SDXL_POINTWISE_LOSS="$TRAIN_SDXL_POINTWISE_LOSS" \
    TRAIN_SDXL_HUBER_DELTA="$TRAIN_SDXL_HUBER_DELTA" \
    TRAIN_SDXL_PROMPT_COSINE_WEIGHT="$TRAIN_SDXL_PROMPT_COSINE_WEIGHT" \
    TRAIN_SDXL_POOLED_COSINE_WEIGHT="$TRAIN_SDXL_POOLED_COSINE_WEIGHT" \
    TRAIN_SDXL_PROMPT_NORM_WEIGHT="$TRAIN_SDXL_PROMPT_NORM_WEIGHT" \
    TRAIN_SDXL_POOLED_NORM_WEIGHT="$TRAIN_SDXL_POOLED_NORM_WEIGHT" \
    TRAIN_SDXL_PROMPT_NORM_MATCH_WEIGHT="$TRAIN_SDXL_PROMPT_NORM_MATCH_WEIGHT" \
    TRAIN_SDXL_POOLED_NORM_MATCH_WEIGHT="$TRAIN_SDXL_POOLED_NORM_MATCH_WEIGHT" \
    TRAIN_STANDARDIZE_EMBEDDINGS="$TRAIN_STANDARDIZE_EMBEDDINGS" \
    TRAIN_STANDARDIZATION_EPS="$TRAIN_STANDARDIZATION_EPS" \
    TRAIN_STANDARDIZATION_THREADS="$TRAIN_STANDARDIZATION_THREADS" \
    TRAIN_CACHE_STANDARDIZED_ARCHIVES="$TRAIN_CACHE_STANDARDIZED_ARCHIVES" \
    TRAIN_STANDARDIZED_ARCHIVE_CACHE_DIR="$TRAIN_STANDARDIZED_ARCHIVE_CACHE_DIR" \
    TRAIN_STANDARDIZED_ARCHIVE_COMPRESS="$TRAIN_STANDARDIZED_ARCHIVE_COMPRESS" \
    TRAIN_STANDARDIZED_ARCHIVE_CACHE_DTYPE="$TRAIN_STANDARDIZED_ARCHIVE_CACHE_DTYPE" \
    TRAIN_SDXL_MONITOR_METRIC="$TRAIN_SDXL_MONITOR_METRIC" \
    TRAIN_SDXL_MONITOR_NORM_WEIGHT="$TRAIN_SDXL_MONITOR_NORM_WEIGHT" \
    TRAIN_SDXL_MONITOR_STD_WEIGHT="$TRAIN_SDXL_MONITOR_STD_WEIGHT" \
    TRAIN_SDXL_MONITOR_PROMPT_NORM_MATCH_WEIGHT="$TRAIN_SDXL_MONITOR_PROMPT_NORM_MATCH_WEIGHT" \
    TRAIN_SDXL_MONITOR_POOLED_NORM_MATCH_WEIGHT="$TRAIN_SDXL_MONITOR_POOLED_NORM_MATCH_WEIGHT" \
    TRAIN_SDXL_PROJECTOR_ARCH="$TRAIN_SDXL_PROJECTOR_ARCH" \
    TRAIN_SDXL_SPECTRAL_NORM="$TRAIN_SDXL_SPECTRAL_NORM" \
    TRAIN_SDXL_USE_OUTPUT_CALIBRATOR="$TRAIN_SDXL_USE_OUTPUT_CALIBRATOR" \
    TRAIN_SDXL_PROMPT_TOKEN_DIM="$TRAIN_SDXL_PROMPT_TOKEN_DIM" \
    TRAIN_SDXL_TRUNK_DEPTH="$TRAIN_SDXL_TRUNK_DEPTH" \
    TRAIN_SDXL_RESIDUAL_TRUNK="$TRAIN_SDXL_RESIDUAL_TRUNK" \
    TRAIN_SDXL_PROMPT_HEAD_DIM="$TRAIN_SDXL_PROMPT_HEAD_DIM" \
    TRAIN_SDXL_POOLED_HEAD_DIM="$TRAIN_SDXL_POOLED_HEAD_DIM" \
    TRAIN_SDXL_RESAMPLER_DEPTH="$TRAIN_SDXL_RESAMPLER_DEPTH" \
    TRAIN_SDXL_RESAMPLER_HEADS="$TRAIN_SDXL_RESAMPLER_HEADS" \
    TRAIN_SDXL_RESAMPLER_FF_MULT="$TRAIN_SDXL_RESAMPLER_FF_MULT" \
    TRAIN_SDXL_RESAMPLER_POOLED_QUERIES="$TRAIN_SDXL_RESAMPLER_POOLED_QUERIES" \
    TRAIN_PROGRESS_EVERY="$TRAIN_PROGRESS_EVERY" \
    TRAIN_PROGRESS_SECONDS="$TRAIN_PROGRESS_SECONDS" \
    TRAIN_TIMING="$TRAIN_TIMING" \
    TRAIN_WARM_START_PATH="$TRAIN_WARM_START_PATH" \
    TRAIN_WARM_START_STRICT="$TRAIN_WARM_START_STRICT" \
    TRAIN_AUTO_RESUME="$TRAIN_AUTO_RESUME" \
    TRAIN_BEST_CHECKPOINT="$TRAIN_BEST_CHECKPOINT" \
    TRAIN_GGUF_PATH="$TRAIN_GGUF_PATH" \
    TRAIN_RESUME_CHECKPOINT="$TRAIN_RESUME_CHECKPOINT" \
    TRAIN_SDXL_PROMPT_OUTPUT_CALIBRATOR_GAIN_SCALE="$TRAIN_SDXL_PROMPT_OUTPUT_CALIBRATOR_GAIN_SCALE" \
    TRAIN_SDXL_POOLED_OUTPUT_CALIBRATOR_GAIN_SCALE="$TRAIN_SDXL_POOLED_OUTPUT_CALIBRATOR_GAIN_SCALE" \
    uv run python train.py 2>&1 | tee "$LOG_PATH"